version: '3.7'
services:
  testbank:
    build: ./testbank
    ports:
      - '80:3000'
    depends_on:
      - backend
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - PRODUCTION=${PRODUCTION}
      - JWT_SECRET=${JWT_SECRET}
      - DATA_DIR=/srv/data
    volumes:
      - ./data:/srv/data
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'

volumes:
  data:
